name: killer_game_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    # Add this line


  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  generate: true
  assets:
    - assets/images/
    - assets/

  uses-material-design: true

