name: CI/CD KillerGame

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    permissions:
      contents: read
      pages: write  
      
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run widget tests
        run: flutter test test/widget_test.dart

      - name: Run unit tests
        run: flutter test test/unit_test.dart

      - name: Build windows app
        run: flutter build windows

      - name: Build web app
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web